# Generated by Django 4.0.1 on 2022-02-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
