# Generated by Django 4.0.1 on 2022-02-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0006_brand_products_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='orgin',
            new_name='Orgin',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='slug',
            new_name='Slug',
        ),
    ]
