# Generated by Django 4.0.1 on 2022-02-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0007_rename_name_brand_name_rename_orgin_brand_orgin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Slug',
            field=models.SlugField(),
        ),
    ]
