# Generated by Django 4.0.1 on 2022-02-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0008_alter_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='Slug',
        ),
        migrations.AddField(
            model_name='brand',
            name='s_lug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
