# Generated by Django 4.0.1 on 2022-02-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0009_remove_brand_slug_brand_s_lug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='s_lug',
            field=models.SlugField(),
        ),
    ]
