# Generated by Django 4.0.1 on 2022-02-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0011_remove_brand_s_lug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
