# Generated by Django 4.0.1 on 2022-02-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0012_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeup.kind'),
        ),
    ]
