# Generated by Django 4.0.1 on 2022-02-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0013_kind_alter_products_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brands',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
