# Generated by Django 4.0.1 on 2022-02-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0015_brand_products_brands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
