# Generated by Django 4.0.1 on 2022-02-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0016_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
